### ISSUE TITLE
Target Framework

### ISSUE THREAD

**Issue by kfrancis** [Kukks/NNostr#12]
If there's no specific reason, I suggest we bump this down to .net standard 2.0/2.1 so it's more widely usable. This would make it usable in both Xamarin and MAUI.

Otherwise, we should target multiple frameworks.

**Comment by Kukks** [comment]
> If there's no specific reason, I suggest we bump this down to .net standard 2.0/2.1 so it's more widely usable. This would make it usable in both Xamarin and MAUI.
> 
> Otherwise, we should target multiple frameworks.

It seems that the recent improvements have used new methods which arent available in netstandard, such as Convert.FromHex and `DecryptCbc`/`EncryptCbc`

**Comment by Kukks** [comment]
How about net7?

**Comment by kfrancis** [comment]
Sure, but do you mind if I set up multi-target (netstandard2.0, net6.0, net7.0) for the lib? It makes sense if you want to use some newer features, but it would be nice to support the minimum as well.

- netstandard to open it as wide as possible
- net6 for LTS
- net7 for STS

**Comment by Kukks** [comment]
Sure, let's do that
