### ISSUE TITLE
I'm terrible at this

### ISSUE THREAD

**Issue by me639276639936** [Kukks/NNostr#18]
I must have rabies or something. I can't get this to work at all. I barely got dotnet to install on an RPI4 and install the projects. I wasn't able to use any of the client usage steps because it didn't like the ( parentheses.

I did update the docker deployment correctly, but the relay is not available at the .local/nostr URL

Is there like a video tutorial on this or something? Sorry to be a painful noob.

Thanks for all the hard work you've done on the BTCPay project

**Comment by angelonardone** [comment]
How can I run the Relay without BTCPay?
I've downloaded the project, and compiled it.
How do I run it? Is there a documentation? How do I configure it?
Can I run the Relay outside docker?
Thanks
