### ISSUE TITLE
Idea integration with NNostr

### ISSUE THREAD

**Issue by bolzobrazil** [Kukks/NNostr#25]
Hi would these ideas be integrateable with NNostr?
https://github.com/nostr-protocol/nostr/issues/194
https://www.reddit.com/r/TOR/comments/1e4te8m/introducing_discussing_reflectors_as_concept/
https://lists.torproject.org/pipermail/tor-relays/2024-July/021744.htm

**Comment by Kukks** [comment]
why not, but i wont be doing it.
