### ISSUE TITLE
http endoints not reachable

### ISSUE THREAD

**Issue by Nisaba** [Kukks/NNostr#26]
I tried to install the relay on my BTCPay instance.

wss://my-btcpay-instance/nostr works well, relay is reachable in Nostr clients and seems to be fully functional.

but https://my-btcpay-instance/nostr or https://my-btcpay-instance/admin doesn't work, I have a 404 error.

Strange thing, when I tried https://my-btcpay-instance/dqsdqdq I get the BTCPay 404 page with Nicolas picture, but with https://my-btcpay-instance/nostr I get an empty 404 browser page...

Thank you for your help

**Comment by Kukks** [comment]
They are not actual endpoints
