### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by kfrancis** [Kukks/NNostr#4]
What is the simplest way to use this client?

Trying to use in a MAUI app, but it doesn't look like the usage app is complete so it's not super clear how to actually use it. Any chance you can clarify?

**Comment by Kukks** [comment]
Yes, I'll try to whip something together to showcase things soon

**Comment by jpmikkers** [comment]
At least a readme.md would be nice :)

**Comment by kfrancis** [comment]
Just so you know, since I wasn't sure how this library worked and you hadn't been available for a bit, I've been working on one [here](https://github.com/kfrancis/NuSocial/tree/main/src/NostrLib), [NuGet](https://www.nuget.org/packages/NostrLib/0.1.33-alpha-g6a0848af31). I'm happy to either help/collab/whatever. I just want to either use or help with a working .net lib.

**Comment by Kukks** [comment]
We could def reconciliate since it looks like mostly common code.

**Comment by sunht666** [comment]
is this relay using by postgres? any table structures？
I need some readme.md XD

**Comment by TheSameCat2** [comment]
Just wanted to weigh in here and say that I'm very interested in using the client library. Some usage info would be helpful, if you ever get a moment. I would love to contribute anything I add back.

I'm using this in a client I'm building for Nostr - wondering about license as well? I was looking at MIT but would not object to something GPL based.

**Comment by Kukks** [comment]
Added some usage instructions now. Still very basic but enough to get things rolling. Sorry for the delay.
